### ISSUE TITLE
1.10.2 Server Crashed LoaderExceptionModCrash: Caught exception from Recurrent Complex (reccomplex)

### ISSUE THREAD

**Issue by 7934345** [Ivorforce/RecurrentComplex#121]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.10.2-4.2.7.jar)
  CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  IvToolkit (IvToolkit-1.2.8.5.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  CorePlugin (FluxedRedstone-2.5.0.51.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 11/23/16 5:17 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Recurrent Complex (reccomplex)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class ivorius.reccomplex.RCConfig
	at ivorius.reccomplex.RecurrentComplex.preInit(RecurrentComplex.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 3.10.0-327.36.3.el7.x86_64
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2825925112 bytes (2695 MB) / 3087007744 bytes (2944 MB) up to 3087007744 bytes (2944 MB)
	JVM Flags: 2 total; -Xmx3g -Xms3g
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2151 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge.jar) 
	UCH	Forge{12.18.2.2151} [Minecraft Forge] (forge.jar) 
	UCH	ivtoolkit{1.2.8.5} [IvToolkit] (minecraft.jar) 
	UCH	slimecompendium{1.4} [Slime Compendium] ([1.10.2]SlimeCompendium1.4.jar) 
	UCH	babymobs{1.5.1} [Baby Mobs] (BabyMobs-1.10.2-1.5.1.jar) 
	UCH	BiomesOPlenty{5.0.0.2109} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2109-universal.jar) 
	UCH	infinitylib{1.10.2-0.2.1} [InfinityLib] (infinitylib-0.2.1.jar) 
	UCH	boatifull{@MAJOR@.@MINOR@.@REVIS@} [Boatifull] (boatifull-0.2.jar) 
	UCH	bookshelf{1.4.3.338} [Bookshelf] (Bookshelf-1.10.2-1.4.3.338.jar) 
	UCH	ChestTransporter{2.5.5} [Chest Transporter] (ChestTransporter-1.10.2-2.5.5.jar) 
	UCH	cxlibrary{1.2.2} [CXLibrary] (cxlibrary-1.10.2-1.2.2.jar) 
	UCH	dldungeonsjdg{1.8.13} [Doomlike Dungeons] (DoomlikeDungeons-1.8.13-MC1.10.jar) 
	UCH	eplus{4.1.0.116} [Enchanting Plus] (EnchantingPlus-1.10.2-4.1.0.116.jar) 
	UCH	endercompass{1.2.3.2} [Ender Compass] (EnderCompass-1.9.x-1.2.3.2.jar) 
	UCH	endercrop{1.9-1.2-1836} [Ender Crop] (endercrop-1.9.4-1.3.1.jar) 
	UCH	EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
	UCH	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCH	reborncore{2.7.3.46} [RebornCore] (RebornCore-1.10.2-2.7.3.46-universal.jar) 
	UCH	reborncore-mcmultipart{2.7.3.46} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.7.3.46-universal.jar) 
	UCH	fluxedredstone{@MODVERSION@} [FluxedRedstone] (FluxedRedstone-2.5.0.51.jar) 
	UCH	glasscraftmod{1.0} [Glasscraft] (Glasscraftmod v1.0 - MC1.10.2 Forge.jar) 
	UCH	helpfixer{1.0} [HelpFixer] (HelpFixer-1.10.2-1.4.15.jar) 
	UCH	hopperducts{1.4.8} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.8.jar) 
	UCH	InfernalMobs{1.7.1} [Infernal Mobs] (InfernalMobs-1.10.jar) 
	UCH	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCH	journeymap{1.10.2-5.3.0} [JourneyMap] (journeymap-1.10.2-5.3.0.jar) 
	UCH	login_shield{1.10.2-17-g972e27d} [Login Shield] (Login_Shield-1.10.2-17-g972e27d.jar) 
	UCH	malisiscore{1.10.2-4.2.7} [MalisisCore] (malisiscore-1.10.2-4.2.7.jar) 
	UCH	malisisblocks{1.10.2-4.1.2} [Malisis Blocks] (malisisblocks-1.10.2-4.1.2.jar) 
	UCH	MoreFurnaces{1.8.2} [More Furnaces] (MoreFurnaces-1.10.2-1.8.2.jar) 
	UCH	Morpheus{1.10.2-3.1.12} [Morpheus] (Morpheus-1.10.2-3.1.12.jar) 
	UCH	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCH	nmsot{1.1.9-mc1.10.2} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.1.9-mc1.10.2.jar) 
	UCH	placemod{3.8} [Placemod] (placemod-3.8-1.10.2.jar) 
	UCH	progressiveautomation{1.6.53} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.53.jar) 
	UCE	reccomplex{1.2.4} [Recurrent Complex] (RecurrentComplex-1.2.4.jar) 
	UCH	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
	UCH	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UCH	AS_Ruins{16.2} [Ruins Spawning System] (Ruins-1.10.2.jar) 
	UCH	valkyrielib{1.10.2-0.10.5d} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.5d.jar) 
	UCH	simplegenerators{1.10.2-0.10.5b} [Simple Generators] (simplegenerators-1.10.2-0.10.5b.jar) 
	UCH	spawnercraft{3.1} [SpawnerCraft] (SpawnerCraft 1.10.2-3.3.1.jar) 
	UCH	storagenetwork{1.12.10} [Storage Network] (StorageNetwork-1.10.2-1.12.10-final.jar) 
	UCH	thutcore{3.9.0} [ThutCore] (thutcore-3.9.0.jar) 
	UCH	thuttech{4.0.10} [Thut's Tech] (thuttech-4.0.10.jar) 
	UCH	trashslot{6.3.6} [TrashSlot] (TrashSlot_1.10.2-6.3.6.jar) 
	UCH	VeinMiner{0.34.1_1.9-73be663} [Vein Miner] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCH	VeinMinerModSupport{0.34.1_1.9-73be663} [Mod Support] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCH	waterstrainer{1.3.2} [Water Strainer] (WaterStrainer-1.9.4-1.3.2.jar) 
	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.10.2-4.2.7.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  cubex2.cxlibrary.CoreModTransformer
IvToolkit (IvToolkit-1.2.8.5.jar)
  
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
CorePlugin (FluxedRedstone-2.5.0.51.jar)
  
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Ivorforce** [comment]
Your version of IvToolkit is outdated.

**Comment by 7934345** [comment]
Oh thx, I try the lasted IvToolkit-1.2.9.jar and everything goes well
