### ISSUE TITLE
[1.10.2] Compatibility with Malisis Doors

### ISSUE THREAD

**Issue by xSparky911x** [Ivorforce/RecurrentComplex#161]
Would love to have compatibility with Malisis Doors. There are some things that work like Rusty Ladder. But if you try to use any of the doors in your structures it throws a bunch of errors. The doors are also non functional. Not sure if this is related to Malisis or RC. Here is the single player game log when the error happens:

[11:47:18] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=top, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=malisisdoors:rustyHatch, properties=[direction, origin, top]}
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=top, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=malisisdoors:rustyHatch, properties=[direction, origin, top]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196) ~[art$a.class:?]
	at net.malisis.doors.block.RustyHatch.func_176201_c(RustyHatch.java:220) ~[RustyHatch.class:1.10.2-5.2.0]
	at net.malisis.core.util.MBlockState.matchesWorld(MBlockState.java:177) ~[MBlockState.class:1.10.2-4.3.0]
	at net.malisis.core.util.multiblock.MultiBlock.breakBlocks(MultiBlock.java:181) ~[MultiBlock.class:1.10.2-4.3.0]
	at net.malisis.core.util.multiblock.MultiBlock.breakBlocks(MultiBlock.java:172) ~[MultiBlock.class:1.10.2-4.3.0]
	at net.malisis.core.util.multiblock.MultiBlockComponent.breakBlock(MultiBlockComponent.java:120) ~[MultiBlockComponent.class:1.10.2-4.3.0]
	at net.malisis.core.block.MalisisBlock.lambda$breakBlock$6(MalisisBlock.java:281) ~[MalisisBlock.class:1.10.2-4.3.0]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_111]
	at net.malisis.core.block.MalisisBlock.func_180663_b(MalisisBlock.java:281) ~[MalisisBlock.class:1.10.2-4.3.0]
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:565) ~[asv.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:331) ~[aid.class:?]
	at net.minecraft.block.Block.removedByPlayer(Block.java:1109) ~[akf.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.removeBlock(PlayerInteractionManager.java:275) ~[lv.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180235_c(PlayerInteractionManager.java:269) ~[lv.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:313) ~[lv.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:158) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:631) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[ja.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[ja.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more

**Comment by Ivorforce** [comment]
Are there any errors when exporting the structure, or just when generating? What about /#import?

**Comment by Ivorforce** [comment]
12a54b3d18715c9e854bd1fe81bebe816a3cfbcf should fix the problem.

Some things still don't work (iron hatches, as they store stuff in the chunk data) - there might be more but I don't know. The basics should work now though :)

**Comment by xSparky911x** [comment]
Awesome! Haven't had a chance to test on export yet sorry

On Feb 21, 2017 10:48 AM, Ivorius <notifications@github.com> wrote:

12a54b3<https://github.com/Ivorforce/RecurrentComplex/commit/12a54b3d18715c9e854bd1fe81bebe816a3cfbcf> should fix the problem.

Some things still don't work (iron hatches, as they store stuff in the chunk data) - there might be more but I don't know. The basics should work now though :)
