### ISSUE TITLE
Previews of big structures crash the game

### ISSUE THREAD

**Issue by talonos2** [Ivorforce/RecurrentComplex#167]
When I use the command /#gen DesertFort, it causes a corrupt world. It crashes you back to the main menu, and then every time you try to open the world, it boots you back to the main menu with the following error:

```
java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
  	at net.minecraft.network.play.server.SPacketCustomPayload.<init>(SPacketCustomPayload.java:27) ~[gl.class:?]
  	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toS3FPackets(FMLProxyPacket.java:156) ~[FMLProxyPacket.class:?]
  	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:531) ~[NetworkDispatcher.class:?]
  	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
  	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
  	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
  	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
  	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
  	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
  	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:247) [eo$4.class:?]
  	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [netty-all-4.0.23.Final.jar:4.0.23.Final]
  	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [netty-all-4.0.23.Final.jar:4.0.23.Final]
  	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-4.0.23.Final.jar:4.0.23.Final]
  	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
```

Perhaps DesertFort is a very large structure created in an earlier MC version, and the packets used to send structures have grown since then?

**Comment by Ivorforce** [comment]
You can 'fix' your world by disabling savePlayerCache and reloading it.
You can also avoid it by running /#preview none before doing the /#gen. It's purely an issue with large previews.
