### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by ArmoredCreeper97** [Ivorforce/RecurrentComplex#220]
Have a look at this...(I use 32 other mods too).

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 6/13/17 3:50 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.block.model.FaceBakery.func_178404_a(FaceBakery.java:202)
	at net.minecraft.client.renderer.block.model.FaceBakery.fillVertexData(FaceBakery.java:189)
	at net.minecraft.client.renderer.block.model.FaceBakery.makeQuadVertexData(FaceBakery.java:112)
	at net.minecraft.client.renderer.block.model.FaceBakery.makeBakedQuad(FaceBakery.java:76)
	at net.minecraft.client.renderer.block.model.FaceBakery.func_178414_a(FaceBakery.java:58)
	at BlockModelUtils.makeBakedQuad(BlockModelUtils.java:84)
	at BlockModelUtils.makeModelCube(BlockModelUtils.java:61)
	at BetterGrass.update(BetterGrass.java:73)
	at TextureUtils.resourcesReloaded(TextureUtils.java:295)
	at TextureUtils$1.func_110549_a(TextureUtils.java:338)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at TextureUtils.registerResourceListener(TextureUtils.java:342)
	at net.minecraft.client.renderer.EntityRenderer.frameInit(EntityRenderer.java:2751)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1282)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 110022576 bytes (104 MB) / 318607360 bytes (303 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2282 Optifine OptiFine_1.11.2_HD_U_B7 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2282.jar) 
	U	forge{13.20.0.2282} [Minecraft Forge] (forge-1.11.2-13.20.0.2282.jar) 
	U	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	U	blockdispenser{1.0} [BlockDispenser] (BlockDispenser-1.1-2.jar) 
	U	cyclopscore{0.10.4} [Cyclops Core] (CyclopsCore-1.11.2-0.10.4.jar) 
	U	denseores{1.0} [denseores] (denseores-1.11-1.0.2.jar) 
	U	durabilityshow{4.1.0} [Durability Show] (Durability Show-1.11.2-4.1.0.jar) 
	U	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.4.1.jar) 
	U	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	U	jei{4.4.0.283} [Just Enough Items] (jei_1.11.2-4.4.0.283.jar) 
	U	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	U	llor{1.1.3-mc1.11.2} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.3-mc1.11.2.jar) 
	U	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	U	mob_grinding_utils{0.2.0} [mob_grinding_utils] (MobGrindingUtils-0.2.0.jar) 
	U	neat{1.4-13} [Neat] (Neat 1.4-13.jar) 
	U	recipes{1.0.0} [Recipes] (Recipes.jar) 
	U	reccomplex{1.3.2} [Recurrent Complex] (RecurrentComplex-1.3.2.jar) 
	U	substratum{1.9.2.0} [Substratum] (Substratum-1.11.2-1.9.2.0.jar) 
	U	tconstruct{1.11.2-2.7.0.26} [Tinkers' Construct] (TConstruct-1.11.2-2.7.0.26.jar) 
	U	tinkersaddons{1.0.5} [Tinkers' Addons] (Tinkers' Addons-1.11.x-1.0.5.jar) 
	U	veinminer{0.35.3} [Vein Miner] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	U	veinminermodsupport{0.35.3} [Mod Support] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	U	waila{1.7.1} [waila] (Waila-1.7.1_1.11.2.jar) 
	U	wailaharvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.11-1.1.9.jar) 
	U	wawla{2.4.0.231} [What Are We Looking At] (Wawla-1.11.2-2.4.0.231.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4550' Renderer: 'Intel(R) HD Graphics 520'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2282
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 520 GL version 4.4.0 - Build 21.20.16.4550, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_B7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 21.20.16.4550
	OpenGlRenderer: Intel(R) HD Graphics 520
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by Ivorforce** [comment]
Please report this to the BetterGrass authors.
