### ISSUE TITLE
[1.10.2] Error when generating chunks

### ISSUE THREAD

**Issue by Eufranio** [Ivorforce/RecurrentComplex#233]
When my chunks are generating, I get this error sometimes:

```
>  [23:58:23] [Server thread/ERROR] [FML]: A TileEntity type ivorius.reccomplex.block.TileEntityBlockScript has throw an exception trying to write state. It w
ill not persist. Report this to the mod author
java.lang.RuntimeException: class ivorius.reccomplex.block.TileEntityBlockScript is missing a mapping! This is a bug!
    at net.minecraft.tileentity.TileEntity.func_189516_d(TileEntity.java:81) ~[aqk.class:?]
    at net.minecraft.tileentity.TileEntity.func_189515_b(TileEntity.java:72) ~[aqk.class:?]
    at ivorius.reccomplex.block.TileEntityBlockScript.func_189515_b(TileEntityBlockScript.java:44) ~[TileEntityBlockScript.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:384) [atj.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:175) [atj.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:199) [lr.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:805) [lr.class:?]
    at net.minecraft.server.MinecraftServer.redirect$onUpdateTimeLightAndEntitiesGetEntityTracker$zhn000(MinecraftServer.java:3766) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```
I'm running it in a SpongeForge environment, with RecurrentComplex 1.4.1-1.10 and IvToolkit-1.3.3-1.10.
Should I worry about it? Let me know if you need any more info.

**Comment by PugLyf** [comment]
This looks like the bug that was going on in version 1.4. Have you tried 1.4.1?

**Comment by Eufranio** [comment]
Yes, `with RecurrentComplex 1.4.1-1.10 and IvToolkit-1.3.3-1.10`

**Comment by Ivorforce** [comment]
Linking this up to #215. I'm surprised this still happens. I'm guessing you're in lightweight mode too?

**Comment by Eufranio** [comment]
Yea.
