### ISSUE TITLE
crash why exploring world(1.12.2)

### ISSUE THREAD

**Issue by SDUBZ** [Ivorforce/RecurrentComplex#297]
Forge: 1.12.2-2575
RC: RecurrentComplex-1.4.6

crash report:
[crash-2017-12-26_15.52.15-server.txt](https://github.com/Ivorforce/RecurrentComplex/files/1586598/crash-2017-12-26_15.52.15-server.txt)

**Comment by nmarshall23** [comment]
With the same version of Forge and RC.

I'm getting similar errors. 
~~~
java.lang.Error
	at ivorius.reccomplex.commands.RCCommands.onServerStart(RCCommands.java:129)
	at ivorius.reccomplex.RecurrentComplex.onServerStart(RecurrentComplex.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~~~

In fact removing Recurrent Complex bumps up my FPS by 10 or 15.

**Comment by Ivorforce** [comment]
I think your VM settings may be off. Try increasing the space MC gets.
