### ISSUE TITLE
Spawn Command Blocks error

### ISSUE THREAD

**Issue by fishmealx** [Ivorforce/RecurrentComplex#33]
[04:46:42] [Server thread/ERROR]: Couldn't process command: 'setblock ~ ~ ~ mob_spawner 0 replace {EntityId:Zombie}'
java.lang.NullPointerException
	at net.minecraft.command.server.CommandSetBlock.func_71515_b(SourceFile:49) ~[bm.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
	at ivorius.reccomplex.blocks.SpawnCommandLogic.executeCommand(SpawnCommandLogic.java:76) [SpawnCommandLogic.class:?]
	at ivorius.reccomplex.blocks.TileEntitySpawnCommand.generate(TileEntitySpawnCommand.java:103) [TileEntitySpawnCommand.class:?]
	at ivorius.reccomplex.blocks.TileEntitySpawnCommand.generate(TileEntitySpawnCommand.java:35) [TileEntitySpawnCommand.class:?]
	at ivorius.reccomplex.structures.generic.GenericStructureInfo.generate(GenericStructureInfo.java:226) [GenericStructureInfo.class:?]
	at ivorius.reccomplex.structures.generic.GenericStructureInfo.generate(GenericStructureInfo.java:56) [GenericStructureInfo.class:?]
	at ivorius.reccomplex.worldgen.StructureGenerator.instantly(StructureGenerator.java:93) [StructureGenerator.class:?]
	at ivorius.reccomplex.structures.OperationGenerateStructure.perform(OperationGenerateStructure.java:74) [OperationGenerateStructure.class:?]
	at ivorius.reccomplex.entities.StructureEntityInfo.performOperation(StructureEntityInfo.java:137) [StructureEntityInfo.class:?]
	at ivorius.reccomplex.commands.CommandConfirm.func_71515_b(CommandConfirm.java:42) [CommandConfirm.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[04:46:42] [Server thread/ERROR]: Couldn't process command: 'setblock ~ ~ ~ mob_spawner 0 replace {EntityId:Zombie}'
java.lang.NullPointerException
	at net.minecraft.command.server.CommandSetBlock.func_71515_b(SourceFile:49) ~[bm.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
	at ivorius.reccomplex.blocks.SpawnCommandLogic.executeCommand(SpawnCommandLogic.java:76) [SpawnCommandLogic.class:?]
	at ivorius.reccomplex.blocks.TileEntitySpawnCommand.generate(TileEntitySpawnCommand.java:103) [TileEntitySpawnCommand.class:?]
	at ivorius.reccomplex.blocks.TileEntitySpawnCommand.generate(TileEntitySpawnCommand.java:35) [TileEntitySpawnCommand.class:?]
	at ivorius.reccomplex.structures.generic.GenericStructureInfo.generate(GenericStructureInfo.java:226) [GenericStructureInfo.class:?]
	at ivorius.reccomplex.structures.generic.GenericStructureInfo.generate(GenericStructureInfo.java:56) [GenericStructureInfo.class:?]
	at ivorius.reccomplex.worldgen.StructureGenerator.instantly(StructureGenerator.java:93) [StructureGenerator.class:?]
	at ivorius.reccomplex.structures.OperationGenerateStructure.perform(OperationGenerateStructure.java:74) [OperationGenerateStructure.class:?]
	at ivorius.reccomplex.entities.StructureEntityInfo.performOperation(StructureEntityInfo.java:137) [StructureEntityInfo.class:?]
	at ivorius.reccomplex.commands.CommandConfirm.func_71515_b(CommandConfirm.java:42) [CommandConfirm.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

Edit:
Here is a 30 second video demonstrating the issue(s):
https://www.youtube.com/watch?v=skr2jJGo_Bo&feature=youtu.be

**Comment by Ivorforce** [comment]
Does the problem persist in the current dailies? The code changed a good bit since then and the current crash report doesn't apply to the changed logic anymore.

**Comment by Ivorforce** [comment]
Closing due to API changes / likely having already been fixed. Please reopen a new issue if this happens again.
