### ISSUE TITLE
Exception terraingen.SaplingGrowTreeEvent--Server crash

### ISSUE THREAD

**Issue by AdaraChristine** [Ivorforce/RecurrentComplex#331]
RecurrentComplex-1.4.7
Forge-1.12.2-14.23.3.2697

[14:59:16] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.terraingen.SaplingGrowTreeEvent@518fa2e8:
java.lang.NullPointerException: null
	at com.pg85.otg.forge.events.SaplingListener.getSaplingGen(SaplingListener.java:288) ~[SaplingListener.class:?]
	at com.pg85.otg.forge.events.SaplingListener.onSaplingGrow(SaplingListener.java:178) ~[SaplingListener.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1322_SaplingListener_onSaplingGrow_SaplingGrowTreeEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.event.terraingen.TerrainGen.saplingGrowTree(TerrainGen.java:108) [TerrainGen.class:?]
	at net.minecraft.block.BlockSapling.func_176476_e(BlockSapling.java:78) [atp.class:?]
	at net.minecraft.block.BlockSapling.func_176478_d(BlockSapling.java:72) [atp.class:?]
	at net.minecraft.block.BlockSapling.func_180650_b(BlockSapling.java:59) [atp.class:?]
	at net.minecraft.block.Block.func_180645_a(Block.java:508) [aow.class:?]
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476) [oo.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[14:59:16] [Server thread/ERROR] [FML]: Index: 3 Listeners:
[14:59:16] [Server thread/ERROR] [FML]: 0: NORMAL
[14:59:16] [Server thread/ERROR] [FML]: 1: ASM: ivorius.reccomplex.events.handlers.RCTerrainGenEventHandler@4f590159 onSaplingGrow(Lnet/minecraftforge/event/terraingen/SaplingGrowTreeEvent;)V
[14:59:16] [Server thread/ERROR] [FML]: 2: ASM: hellfirepvp.astralsorcery.common.util.TreeCaptureHelper@499624c8 onTreeGrowth(Lnet/minecraftforge/event/terraingen/SaplingGrowTreeEvent;)V
[14:59:16] [Server thread/ERROR] [FML]: 3: ASM: com.pg85.otg.forge.events.SaplingListener@6f79dfe4 onSaplingGrow(Lnet/minecraftforge/event/terraingen/SaplingGrowTreeEvent;)V
[14:59:16] [Server thread/ERROR] [FML]: 4: ASM: shetiphian.terraqueous.common.misc.EventHandler$ForgeTerrainBus@2a304e3b saplingGrowTreeEvent(Lnet/minecraftforge/event/terraingen/SaplingGrowTreeEvent;)V
[14:59:16] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:762) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
	at com.pg85.otg.forge.events.SaplingListener.getSaplingGen(SaplingListener.java:288) ~[SaplingListener.class:?]
	at com.pg85.otg.forge.events.SaplingListener.onSaplingGrow(SaplingListener.java:178) ~[SaplingListener.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1322_SaplingListener_onSaplingGrow_SaplingGrowTreeEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.event.terraingen.TerrainGen.saplingGrowTree(TerrainGen.java:108) ~[TerrainGen.class:?]
	at net.minecraft.block.BlockSapling.func_176476_e(BlockSapling.java:78) ~[atp.class:?]
	at net.minecraft.block.BlockSapling.func_176478_d(BlockSapling.java:72) ~[atp.class:?]
	at net.minecraft.block.BlockSapling.func_180650_b(BlockSapling.java:59) ~[atp.class:?]
	at net.minecraft.block.Block.func_180645_a(Block.java:508) ~[aow.class:?]
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476) ~[oo.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) ~[MinecraftServer.class:?]
https://pastebin.com/wU4hHXiV

**Comment by Ivorforce** [comment]
Have you tried reporting this to the otg authors? I don't think it's ReC related. If they direct you back to me, please re-open the issue :)
