### ISSUE TITLE
Error trying to emulate vanilla decoration

### ISSUE THREAD

**Issue by fcpwiz** [Ivorforce/RecurrentComplex#336]
```
> [14:46:56] [Server thread/ERROR] [reccomplex]: Error trying to emulate vanilla decoration
java.lang.NullPointerException: null
at thaumcraft.common.world.objects.WorldGenBigMagicTree.func_181631_a(WorldGenBigMagicTree.java:116) ~[WorldGenBigMagicTree.class:?]
at thaumcraft.common.world.objects.WorldGenBigMagicTree.generateLeafNode(WorldGenBigMagicTree.java:161) ~[WorldGenBigMagicTree.class:?]
at thaumcraft.common.world.objects.WorldGenBigMagicTree.func_175941_b(WorldGenBigMagicTree.java:218) ~[WorldGenBigMagicTree.class:?]
at thaumcraft.common.world.objects.WorldGenBigMagicTree.func_180709_b(WorldGenBigMagicTree.java:311) ~[WorldGenBigMagicTree.class:?]
at ivorius.reccomplex.world.gen.feature.decoration.VanillaDecorationAdapter.generate(VanillaDecorationAdapter.java:82) [VanillaDecorationAdapter.class:?]
at ivorius.reccomplex.world.gen.feature.decoration.RCBiomeDecorator.doDecorate(RCBiomeDecorator.java:79) [RCBiomeDecorator.class:?]
at ivorius.reccomplex.world.gen.feature.decoration.RCBiomeDecorator.decorate(RCBiomeDecorator.java:51) [RCBiomeDecorator.class:?]
at ivorius.reccomplex.events.handlers.RCTerrainGenEventHandler.onDecoration(RCTerrainGenEventHandler.java:102) [RCTerrainGenEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_787_RCTerrainGenEventHandler_onDecoration_Decorate.invoke(.dynamic) [?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:662) [EventBus.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:597) [EventBus.class:?]
at net.minecraftforge.event.terraingen.TerrainGen.decorate(TerrainGen.java:88) [TerrainGen.class:?]
at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:130) [ank.class:?]
at net.minecraft.world.biome.BiomeDecorator.func_180292_a(BiomeDecorator.java:88) [ank.class:?]
at net.minecraft.world.biome.Biome.func_180624_a(Biome.java:225) [anh.class:?]
at thaumcraft.common.world.biomes.BiomeGenMagicalForest.func_180624_a(BiomeGenMagicalForest.java:156) [BiomeGenMagicalForest.class:?]
at biomesoplenty.common.world.ChunkGeneratorOverworldBOP.func_185931_b(ChunkGeneratorOverworldBOP.java:564) [ChunkGeneratorOverworldBOP.class:?]
at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:269) [SpongeChunkGeneratorForge.class:1.12.2-2705-7.1.0-BETA-3235]
at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017) [axw.class:?]
at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:988) [axw.class:?]
at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157) [on.class:?]
at net.minecraft.world.World.func_72964_e(World.java:309) [amu.class:?]
at net.minecraft.world.World.func_175726_f(World.java:304) [amu.class:?]
at net.minecraft.world.WorldServer.func_180495_p(WorldServer.java:3197) [oo.class:?]
at thaumcraft.common.lib.utils.Utils.isWoodLog(Utils.java:179) [Utils.class:?]
at thaumcraft.common.world.biomes.BiomeGenMagicalForest.isBlockAdjacentToWood(BiomeGenMagicalForest.java:185) [BiomeGenMagicalForest.class:?]
at thaumcraft.common.world.biomes.BiomeGenMagicalForest.func_180624_a(BiomeGenMagicalForest.java:171) [BiomeGenMagicalForest.class:?]
at biomesoplenty.common.world.ChunkGeneratorOverworldBOP.func_185931_b(ChunkGeneratorOverworldBOP.java:564) [ChunkGeneratorOverworldBOP.class:?]
at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:269) [SpongeChunkGeneratorForge.class:1.12.2-2705-7.1.0-BETA-3235]
at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017) [axw.class:?]
at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:988) [axw.class:?]
at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157) [on.class:?]
at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$bba000(PlayerChunkMapEntry.java:1079) [ot.class:?]
at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126) [ot.class:?]
at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147) [ou.class:?]
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227) [oo.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by Ivorforce** [comment]
I recommend reporting this to thaumcraft. It's not out of the question ReC has some problem here as well, but thaumcraft should have a better handle on fixing this issue.

If they direct you back to me, please re-open the issue and I will talk with them :)

**Comment by JumboTSB** [comment]
Hey there, I was wondering if you have any insights to solve this issue. The thaumcraft developer abandoned the project years ago and this is seemingly the only issue my server runs into when using recurrent complex. The error is seemingly the same or at least very similar. https://pastebin.com/467Z1V7f
I've also tried enabling lightweight mode to no avail.
