### ISSUE TITLE
/#move command giving "unknown error"

### ISSUE THREAD

**Issue by Liruilos** [Ivorforce/RecurrentComplex#338]
All other RecCom commands working perfectly, but for /#move after clicking on or typing confirm it responds with "An unknown error occurred while attempting to perform this command". Tested with vanilla full blocks only, moving into air, or onto the ground, or even not actually moving anywhere, it still gives this error. Having the issue both on our server and in single player world. Any ideas?

Server log showing the error:

```
java.lang.NullPointerException: null
	at ivorius.reccomplex.utils.ItemHandlers.getModifiable(ItemHandlers.java:49) ~[ItemHandlers.class:?]
	at ivorius.reccomplex.utils.ItemHandlers.hasModifiable(ItemHandlers.java:44) ~[ItemHandlers.class:?]
	at ivorius.reccomplex.utils.ItemHandlers.hasModifiable(ItemHandlers.java:57) ~[ItemHandlers.class:?]
	at ivorius.reccomplex.operation.OperationClearArea.emptyOut(OperationClearArea.java:54) ~[OperationClearArea.class:?]
	at ivorius.reccomplex.operation.OperationClearArea.setBlockToAirClean(OperationClearArea.java:47) ~[OperationClearArea.class:?]
	at ivorius.reccomplex.operation.OperationClearArea.perform(OperationClearArea.java:84) ~[OperationClearArea.class:?]
	at ivorius.reccomplex.operation.OperationMulti.lambda$perform$0(OperationMulti.java:45) ~[OperationMulti.class:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_111]
	at ivorius.reccomplex.operation.OperationMulti.perform(OperationMulti.java:45) ~[OperationMulti.class:?]
	at ivorius.reccomplex.capability.RCEntityInfo.performOperation(RCEntityInfo.java:122) ~[RCEntityInfo.class:?]
	at ivorius.reccomplex.commands.preview.CommandConfirm.func_184881_a(CommandConfirm.java:36) ~[CommandConfirm.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

Screenshot:
![2018-07-14_11 49 22](https://user-images.githubusercontent.com/33904574/42723426-c9a2b424-875d-11e8-8dd1-f0fef42aaa36.png)

**Comment by Ivorforce** [comment]
Should be easy enough to fix. I'll be looking into this for the next update :)

**Comment by Ivorforce** [comment]
Haha wow, I can't believe /#move just didn't work at in the latest version. I fixed it now, thanks for the report!

**Comment by Liruilos** [comment]
cool, thanks for the update!
