### ISSUE TITLE
Crash when structure saving is disabled

### ISSUE THREAD

**Issue by Sir-Will** [Ivorforce/RecurrentComplex#362]
When disabling structure saving RecurrentComplex causes this crash.

RecurrentComplex-1.4.7.jar
BiomesOPlenty-1.12.2-7.0.1.2422-universal
```
java.lang.NullPointerException: Exception in server tick loop
	at ivorius.reccomplex.world.gen.feature.structure.MapGenStructureHook.func_143025_a(MapGenStructureHook.java:88)
	at net.minecraft.world.gen.structure.MapGenStructure.handler$onConstruction$bae003(MapGenStructure.java:1063)
	at net.minecraft.world.gen.structure.MapGenStructure.<init>(MapGenStructure.java:24)
	at ivorius.reccomplex.world.gen.feature.structure.MapGenStructureHook.<init>(MapGenStructureHook.java:37)
	at ivorius.reccomplex.events.handlers.RCTerrainGenEventHandler.onInitMapGen(RCTerrainGenEventHandler.java:292)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1563_RCTerrainGenEventHandler_onInitMapGen_InitMapGenEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:687)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:641)
	at net.minecraftforge.event.terraingen.TerrainGen.getModdedMapGen(TerrainGen.java:48)
	at biomesoplenty.common.world.ChunkGeneratorOverworldBOP.<init>(ChunkGeneratorOverworldBOP.java:99)
	at biomesoplenty.common.world.WorldTypeBOP.getChunkGenerator(WorldTypeBOP.java:38)
	at net.minecraft.world.WorldProvider.func_186060_c(WorldProvider.java:63)
	at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:848)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:118)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3545)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at ivorius.reccomplex.world.gen.feature.structure.MapGenStructureHook.func_143025_a(MapGenStructureHook.java:88)
	at net.minecraft.world.gen.structure.MapGenStructure.handler$onConstruction$bae003(MapGenStructure.java:1063)
	at net.minecraft.world.gen.structure.MapGenStructure.<init>(MapGenStructure.java:24)
	at ivorius.reccomplex.world.gen.feature.structure.MapGenStructureHook.<init>(MapGenStructureHook.java:37)
	at ivorius.reccomplex.events.handlers.RCTerrainGenEventHandler.onInitMapGen(RCTerrainGenEventHandler.java:292)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1563_RCTerrainGenEventHandler_onInitMapGen_InitMapGenEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:687)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:641)
	at net.minecraftforge.event.terraingen.TerrainGen.getModdedMapGen(TerrainGen.java:48)
	at biomesoplenty.common.world.ChunkGeneratorOverworldBOP.<init>(ChunkGeneratorOverworldBOP.java:99)
	at biomesoplenty.common.world.WorldTypeBOP.getChunkGenerator(WorldTypeBOP.java:38)
	at net.minecraft.world.WorldProvider.func_186060_c(WorldProvider.java:63)
	at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:848)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:118)
```

**Comment by LXGaming** [comment]
Fix available here: https://github.com/lolnetnz/RecurrentComplex/releases/tag/v1.4.7

**Comment by Ivorforce** [comment]
Cool, thanks for the fix. I will integrate it in the next update =)

**Comment by Ivorforce** [comment]
Well, imo it's super unfair that whoever core-patched this method calls a method before I get a chance to init, but whatever. Should be fixed.
