### ISSUE TITLE
OpenComputers support

### ISSUE THREAD

**Issue by Gliese-832-c** [Ivorforce/RecurrentComplex#449]
OpenComputers computers don't get generated, and corrupt the whole structure.
![grafik](https://user-images.githubusercontent.com/55159077/88966032-f6330200-d2ab-11ea-91d5-70e7ca39fa3f.png)
![grafik](https://user-images.githubusercontent.com/55159077/88966069-0814a500-d2ac-11ea-9faa-c85cc0bb93f6.png)
![grafik](https://user-images.githubusercontent.com/55159077/88966095-12cf3a00-d2ac-11ea-96da-9c09d415e389.png)

**Comment by otakup0pe** [comment]
Oh would love to see this. I've spent some time troubleshooting it and on my modpack (1.12 based) there are errors when exporting the computers, and then very few things get imported. I'll try digging up some logs this weekend.

**Comment by otakup0pe** [comment]
Looks like the problems occur when you try to re-import a powered computer with components inside?

```
[12:53:41] [Server thread/ERROR] [reccomplex]: Error on structure generation
java.lang.IllegalStateException: Loading data after part of a grid, this is invalid.
        at appeng.me.GridNode.loadFromNBT(GridNode.java:344) ~[GridNode.class:?]
        at li.cil.oc.common.tileentity.traits.power.AppliedEnergistics2$class.loadNode(AppliedEnergistics2.scala:74) ~[AppliedEnergistics2$class.class:?]
        at li.cil.oc.common.tileentity.traits.power.AppliedEnergistics2$class.readFromNBTForServer(AppliedEnergistics2.scala:69) ~[AppliedEnergistics2$class.class:?]
        at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$Environment$$super$readFromNBTForServer(Case.scala:28) ~[Case.class:?]
        at li.cil.oc.common.tileentity.traits.Environment$class.readFromNBTForServer(Environment.scala:62) ~[Environment$class.class:?]
        at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$Inventory$$super$readFromNBTForServer(Case.scala:28) ~[Case.class:?]
        at li.cil.oc.common.tileentity.traits.Inventory$class.readFromNBTForServer(Inventory.scala:22) ~[Inventory$class.class:?]
        at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$RedstoneAware$$super$readFromNBTForServer(Case.scala:28) ~[Case.class:?]
        at li.cil.oc.common.tileentity.traits.RedstoneAware$class.readFromNBTForServer(RedstoneAware.scala:137) ~[RedstoneAware$class.class:?]
        at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$BundledRedstoneAware$$super$readFromNBTForServer(Case.scala:28) ~[Case.class:?]
        at li.cil.oc.common.tileentity.traits.BundledRedstoneAware$class.readFromNBTForServer(BundledRedstoneAware.scala:155) ~[BundledRedstoneAware$class.class:?]
        at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$Computer$$super$readFromNBTForServer(Case.scala:28) ~[Case.class:?]
        at li.cil.oc.common.tileentity.traits.Computer$class.readFromNBTForServer(Computer.scala:144) ~[Computer$class.class:?]
        at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$Colored$$super$readFromNBTForServer(Case.scala:28) ~[Case.class:?]
        at li.cil.oc.common.tileentity.traits.Colored$class.readFromNBTForServer(Colored.scala:38) ~[Colored$class.class:?]
        at li.cil.oc.common.tileentity.Case.readFromNBTForServer(Case.scala:100) ~[Case.class:?]
        at li.cil.oc.common.tileentity.traits.TileEntity$class.readFromNBT(TileEntity.scala:90) ~[TileEntity$class.class:?]
        at li.cil.oc.common.tileentity.Case.func_145839_a(Case.scala:28) ~[Case.class:?]
        at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.setBlock(GenericStructure.java:123) ~[GenericStructure.class:?]
        at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.generate(GenericStructure.java:214) ~[GenericStructure.class:?]
        at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.generate(GenericStructure.java:71) ~[GenericStructure.class:?]
        at ivorius.reccomplex.world.gen.feature.StructureGenerator.generate(StructureGenerator.java:168) [StructureGenerator.class:?]
        at ivorius.reccomplex.operation.OperationGenerateStructure.perform(OperationGenerateStructure.java:120) [OperationGenerateStructure.class:?]
        at ivorius.reccomplex.operation.OperationRegistry.queueOperation(OperationRegistry.java:107) [OperationRegistry.class:?]
        at ivorius.reccomplex.commands.structure.CommandGenerateStructure.func_184881_a(CommandGenerateStructure.java:100) [CommandGenerateStructure.class:?]
        at com.feed_the_beast.ftbutilities.ranks.CommandOverride.func_184881_a(CommandOverride.java:83) [CommandOverride.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_241]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_241]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
```
