### ISSUE TITLE
V 0.9.7.4 doesn't seem to work serverside

### ISSUE THREAD

**Issue by Mictali** [Ivorforce/RecurrentComplex#67]
I tried using the 1.8.9 release (with the appropriate IvToolkit).  On single player on my desktop it works just fine, however when I transferred it to work on a server (installed using the forge installer) the game crashes looking for class

        net/minecraft/client/entity/EntityPlayerSP

which of course is not available in the server jar.  I did some digging through both the forge 1.8.9 source and your source, can't find reference to the EntityPlayerSP so it must be coming in sideways.  The specific line of code that appears to be throwing the error is

    network.registerMessage(PacketEditInventoryGeneratorHandler.class, PacketEditInventoryGenerator.class, 2, Side.CLIENT);

But the PacketEditInvenotryGeneratorHandler class doesn't appear to reference the EntityPlayerSP class.

Forge version I'm using is 1.8.9-11.15.1.1902-1.8.9
ReccurentComplex-0.9.7.4 jar

    Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
            at java.lang.Class.getDeclaredConstructors0(Native Method)
            at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
            at java.lang.Class.getConstructor0(Class.java:3075)
            at java.lang.Class.newInstance(Class.java:412)
            at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.instantiate(SimpleNetworkWrapper.java:146)
            at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.registerMessage(SimpleNetworkWrapper.java:139)
            at ivorius.reccomplex.RecurrentComplex.load(RecurrentComplex.java:130)

**Comment by Ivorforce** [comment]
Try it now - it should be fixed.

**Comment by Mictali** [comment]
Same situation, this time at line 140

    network.registerMessage(PacketEditInventoryGeneratorHandler.class, PacketEditInventoryGenerator.class, 3, Side.SERVER);

Looking at the forge code for the registerMessage it is attempting to instantiate the provided class before it ever considers the Side value that is provided, so is there something in one of those classes that pulls in the EntityPlayerSP?

**Comment by Ivorforce** [comment]
Yes, this was fixed in a commit 2 minutes later ;)

**Comment by Mictali** [comment]
Ok using the 408 build of RecurrentComplex and the 137 build of IvToolkit the error is gone.

Thanks!
